/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.spm.timetablemanagement.form.student_details;

import com.spm.timetablemanagement.models.GeneratedId;
import com.spm.timetablemanagement.util.Constant;
import com.spm.timetablemanagement.util.CreateQuery;
import com.spm.timetablemanagement.util.DBconnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/** 
 *
 * @author hvdil
 */
public class groupId_generate extends javax.swing.JPanel {
    
    Connection connection;
    PreparedStatement pstYns, pstDp, pstGno, pst, pst2;
    ResultSet rs;
    /**
     * Creates new form groupId_generate
     */
    public groupId_generate() {
        initComponents();
        yNsSelection();
        dpSelection();
        gNoSelection();
        showGeneratedIdList();
        txt_id.setVisible(false);
        gid.setVisible(false);
        yns_id.setVisible(false);
        dp_id.setVisible(false);
        gno_id.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_gId = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_id = new javax.swing.JTextField();
        gid = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btn_generate_gId = new javax.swing.JButton();
        btn_editGid = new javax.swing.JButton();
        btn_deleteGid = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        select_yNs = new javax.swing.JComboBox<>();
        select_dp = new javax.swing.JComboBox<>();
        txt_error = new javax.swing.JLabel();
        select_gn = new javax.swing.JComboBox<>();
        yns_id = new javax.swing.JTextField();
        dp_id = new javax.swing.JTextField();
        gno_id = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        setBackground(new java.awt.Color(100, 149, 237));
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(833, 737));

        jPanel9.setBackground(new java.awt.Color(100, 149, 237));
        jPanel9.setToolTipText("");
        jPanel9.setPreferredSize(new java.awt.Dimension(1133, 688));

        tbl_gId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbl_gId.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Group ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_gId.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbl_gId.getTableHeader().setReorderingAllowed(false);
        tbl_gId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_gIdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_gId);
        if (tbl_gId.getColumnModel().getColumnCount() > 0) {
            tbl_gId.getColumnModel().getColumn(0).setResizable(false);
            tbl_gId.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel1.setBackground(new java.awt.Color(100, 149, 237));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 15, 0));

        jPanel2.setBackground(new java.awt.Color(100, 149, 237));

        txt_id.setText("ID");
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        gid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gidActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(100, 149, 237));

        btn_generate_gId.setBackground(new java.awt.Color(0, 102, 0));
        btn_generate_gId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_generate_gId.setForeground(new java.awt.Color(255, 255, 255));
        btn_generate_gId.setText("Generate");
        btn_generate_gId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btn_generate_gId.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_generate_gId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generate_gIdActionPerformed(evt);
            }
        });

        btn_editGid.setBackground(new java.awt.Color(0, 102, 255));
        btn_editGid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_editGid.setForeground(new java.awt.Color(255, 255, 255));
        btn_editGid.setText("Update");
        btn_editGid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btn_editGid.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_editGid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editGidActionPerformed(evt);
            }
        });

        btn_deleteGid.setBackground(new java.awt.Color(153, 0, 0));
        btn_deleteGid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_deleteGid.setForeground(new java.awt.Color(255, 255, 255));
        btn_deleteGid.setText("Delete");
        btn_deleteGid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btn_deleteGid.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_deleteGid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteGidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(btn_generate_gId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_editGid, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_deleteGid, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_deleteGid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editGid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_generate_gId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(100, 149, 237));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel11.setPreferredSize(new java.awt.Dimension(456, 36));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Academic Year & Semester");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel13.setPreferredSize(new java.awt.Dimension(456, 36));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Group Number");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        select_yNs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Select"}));
        select_yNs.setToolTipText("");
        select_yNs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_yNsActionPerformed(evt);
            }
        });

        select_dp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        select_dp.setToolTipText("");
        select_dp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_dpActionPerformed(evt);
            }
        });

        txt_error.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_error.setForeground(new java.awt.Color(255, 51, 51));
        txt_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        select_gn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        select_gn.setToolTipText("");
        select_gn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_gnActionPerformed(evt);
            }
        });

        yns_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yns_idActionPerformed(evt);
            }
        });

        dp_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dp_idActionPerformed(evt);
            }
        });

        gno_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gno_idActionPerformed(evt);
            }
        });

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel14.setPreferredSize(new java.awt.Dimension(456, 36));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Degree Program");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(select_gn, 0, 99, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(gno_id, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(select_dp, 0, 99, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dp_id, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(select_yNs, 0, 99, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(yns_id, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2))
                    .addComponent(txt_error, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(select_yNs, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(yns_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(select_dp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dp_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(select_gn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gno_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(txt_error, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(gid, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gid, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(390, 390, 390))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(59, 59, 59))
        );

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("GENERATE GROUP ID");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 1064, Short.MAX_VALUE)
                .addGap(1, 1, 1))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 997, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void select_yNsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_yNsActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_select_yNsActionPerformed

    private void select_dpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_dpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_select_dpActionPerformed

    private void select_gnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_gnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_select_gnActionPerformed

    private void tbl_gIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_gIdMouseClicked
        // TODO add your handling code here:
//        int i = tbl_gId.getSelectedRow();
//        TableModel model = tbl_gId.getModel();
//        txt_id.setText(model.getValueAt(i, 0).toString());
        
        int selectedRow = tbl_gId.getSelectedRow();
        int Id = (int) tbl_gId.getValueAt(selectedRow, 0);
        String valueAt = (String) tbl_gId.getValueAt(selectedRow, 1);
        String valuId = String.valueOf(Id);
        txt_id.setText(valuId);

        String[] val = valueAt.split("");

        String first = val[0] + val[1] + val[2] + val[3] + val[4];
        select_yNs.setSelectedItem(first);

        String second = val[6] + val[7];
        select_dp.setSelectedItem(second);

        String third = val[9] + val[10];
        select_gn.setSelectedItem(third);

        TableModel mt = tbl_gId.getModel();
        gid.setText(mt.getValueAt(selectedRow, 1).toString());
    }//GEN-LAST:event_tbl_gIdMouseClicked

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void gidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gidActionPerformed

    private void yns_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yns_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yns_idActionPerformed

    private void dp_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dp_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dp_idActionPerformed

    private void gno_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gno_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gno_idActionPerformed

    private void btn_generate_gIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generate_gIdActionPerformed

        try{
            DefaultTableModel model = (DefaultTableModel)tbl_gId.getModel();
            connection = DBconnection.getConnection();

            if(select_yNs.getSelectedItem().equals("Select")&&select_dp.getSelectedItem().equals("Select")&&select_gn.getSelectedItem().equals("Select")){
                txt_error.setText("Select Items*");
            }
            else{
                txt_error.setText("");

                model.addRow(new Object[]{select_yNs.getSelectedItem().toString()+"."+select_dp.getSelectedItem().toString()+"."+select_gn.getSelectedItem().toString()});

                String getYnsQuery = "select id from academic_year_and_semester where yNs = '"+select_yNs.getSelectedItem().toString()+"'";
                String getDpQuery = "select id from degree_program where dp = '"+select_dp.getSelectedItem().toString()+"'";
                String getGnoQuery = "select id from group_number where gNo = '"+select_gn.getSelectedItem().toString()+"'";

                pstYns = connection.prepareStatement(getYnsQuery);
                rs = pstYns.executeQuery();
                while(rs.next())
                {
                    yns_id.setText(rs.getString("id"));
                }

                pstDp = connection.prepareStatement(getDpQuery);
                rs = pstDp.executeQuery();
                while(rs.next())
                {
                    dp_id.setText(rs.getString("id"));
                }
                pstGno = connection.prepareStatement(getGnoQuery);
                rs = pstGno.executeQuery();
                while(rs.next())
                {
                    gno_id.setText(rs.getString("id"));
                }

                pst = connection.prepareStatement(CreateQuery.getQuery(Constant.INSERT_GROUP_ID_TABLE));

                pst2 = connection.prepareStatement(CreateQuery.getQuery(Constant.INSERT_ALL_DETAILS_TABLE));

                String generateID = (select_yNs.getSelectedItem().toString()+"."+select_dp.getSelectedItem().toString()+"."+select_gn.getSelectedItem().toString());

                pst.setString(1, generateID);
                pst.setString(2, yns_id.getText());
                pst.setString(3, dp_id.getText());
                pst.setString(4, gno_id.getText());

                pst2.setString(1, select_yNs.getSelectedItem().toString());
                pst2.setString(2, select_dp.getSelectedItem().toString());
                pst2.setString(3, select_gn.getSelectedItem().toString());
                pst2.setString(4, generateID);
                pst2.setString(5, "-");

                pst.executeUpdate();
                pst2.executeUpdate();
                model.setRowCount(0);
                showGeneratedIdList();

                select_yNs.setSelectedIndex(0);
                select_dp.setSelectedIndex(0);
                select_gn.setSelectedIndex(0);

                JOptionPane.showMessageDialog(null, "Inserting Successful!");

            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_generate_gIdActionPerformed

    private void btn_editGidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editGidActionPerformed
        String id = txt_id.getText();
        String newGenerateID = (select_yNs.getSelectedItem().toString()+"."+select_dp.getSelectedItem().toString()+"."+select_gn.getSelectedItem().toString());

        try
        {
            DefaultTableModel model = (DefaultTableModel)tbl_gId.getModel();
            Statement smt = connection.createStatement();

            if(txt_id.getText().equals("ID")){
                txt_error.setText("Select Group ID*");
            }
            else{
                txt_error.setText("");

                int i = tbl_gId.getSelectedRow();
                TableModel mt = tbl_gId.getModel();
                gid.setText(mt.getValueAt(i, 1).toString());

                smt.execute("UPDATE generated_group_id SET gId = '"+newGenerateID+"' WHERE id = "+id);
                smt.execute("UPDATE all_details SET gId = '"+newGenerateID+"' WHERE gId = '"+gid.getText().toString()+"' AND sGid = '-' ");
                model.setRowCount(0);
                showGeneratedIdList();

                select_yNs.setSelectedIndex(0);
                select_dp.setSelectedIndex(0);
                select_gn.setSelectedIndex(0);

                JOptionPane.showMessageDialog(this, "Record Updated!");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_editGidActionPerformed

    private void btn_deleteGidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteGidActionPerformed
         String id = txt_id.getText();

        try
        {

            DefaultTableModel model = (DefaultTableModel)tbl_gId.getModel();
            Statement smt = connection.createStatement();

            if(txt_id.getText().equals("ID")){
                txt_error.setText("Select Group ID*");
            }
            else{
                txt_error.setText("");

                int i = tbl_gId.getSelectedRow();
                TableModel mt = tbl_gId.getModel();
                gid.setText(mt.getValueAt(i, 1).toString());

                smt.execute("DELETE FROM generated_group_id WHERE id = "+id);
                smt.execute("DELETE FROM all_details WHERE gId = '"+gid.getText().toString()+"' AND sGid = '-' ");
                model.setRowCount(0);
                showGeneratedIdList();
                JOptionPane.showMessageDialog(this, "Record Deleted!");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_btn_deleteGidActionPerformed

    public  void yNsSelection(){
        try{  
        connection = DBconnection.getConnection();
        String query = "select * from academic_year_and_semester";
        pst = connection.prepareStatement(query);
        rs = pst.executeQuery();
        
        while(rs.next())
        {
            String yNs = rs.getString("yNs");
            select_yNs.addItem(yNs);
        }
        }
        catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e);
        } 
    }
    
    public  void dpSelection(){
        try{  
        connection = DBconnection.getConnection();
        String query = "select * from degree_program";
        pst = connection.prepareStatement(query);
        rs = pst.executeQuery();
        
        while(rs.next())
        {
            String dp = rs.getString("dp");
            select_dp.addItem(dp);
        }
        }
        catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e);
        } 
    }
    
    public  void gNoSelection(){
        try{  
        connection = DBconnection.getConnection();
        String query = "select * from group_number";
        pst = connection.prepareStatement(query);
        rs = pst.executeQuery();
        
        while(rs.next())
        {
            String gNo = rs.getString("gNo");
            select_gn.addItem(gNo);
        }
        }
        catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e);
        } 
    }
    
    public ArrayList<GeneratedId> GetGeneratedIdList()
    {
        ArrayList<GeneratedId> list = new ArrayList<GeneratedId>();
        try{
        connection = DBconnection.getConnection();
        String querry = "select * from generated_group_id";
        Statement st;
        ResultSet rs;
        
        st = connection.createStatement();
        rs= st.executeQuery(querry);
        GeneratedId GID;
        while(rs.next())
        {
            GID = new GeneratedId(rs.getInt("id"), rs.getString("gId"));
            list.add(GID);
        }
        
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        return list;
    }
    
    public void showGeneratedIdList()
    {
        ArrayList<GeneratedId> list = GetGeneratedIdList();
        DefaultTableModel model = (DefaultTableModel)tbl_gId.getModel();
        Object[] row = new Object[2];
        for(int i = 0; i < list.size(); i++)
        {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getGid();
            
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_deleteGid;
    private javax.swing.JButton btn_editGid;
    private javax.swing.JButton btn_generate_gId;
    private javax.swing.JTextField dp_id;
    private javax.swing.JTextField gid;
    private javax.swing.JTextField gno_id;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JComboBox<String> select_dp;
    private javax.swing.JComboBox<String> select_gn;
    private javax.swing.JComboBox<String> select_yNs;
    private javax.swing.JTable tbl_gId;
    private javax.swing.JLabel txt_error;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField yns_id;
    // End of variables declaration//GEN-END:variables
}
