/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.spm.timetablemanagement.form.working_hours;

import com.spm.timetablemanagement.util.Constant;
import com.spm.timetablemanagement.util.CreateQuery;
import com.spm.timetablemanagement.util.DBconnection;
import java.awt.Color;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;

/**
 *
 * @author Tiran Harsha
 */
public class EditWorkingDayHours extends javax.swing.JPanel {

    /**
     * Creates new form EditWorkingDayHours
     */
    public EditWorkingDayHours() {
        initComponents();
        body.removeAll();
//        body.add(new Weekend_Edit());
        body.repaint();
        body.revalidate();
        
//        btn_weekday.setBackground(Color.DARK_GRAY);
//        btn_weekend.setBackground(new Color(153, 153, 0));
    }
    
    public ResultSet getData(int type){
        
        try {
            Connection connection = DBconnection.getConnection();
            PreparedStatement statement = connection.prepareStatement(CreateQuery.getQuery(Constant.GET_WORKING_HOUR_TABLE_BY_TYPE));
        
            statement.setInt(1, type);
            ResultSet rs = statement.executeQuery();
            
            return rs;
        } catch (SQLException | ClassNotFoundException | IOException | ParserConfigurationException | SAXException ex) {
            Logger.getLogger(EditWorkingDayHours.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Cannot load data"+ex.getMessage(), "Data error", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        edit_body = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btn_weekday = new javax.swing.JButton();
        btn_weekend = new javax.swing.JButton();
        body = new javax.swing.JPanel();

        setBackground(new java.awt.Color(100, 149, 237));

        jScrollPane1.setBackground(new java.awt.Color(100, 149, 237));
        jScrollPane1.setBorder(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1310, 570));

        jPanel1.setBackground(new java.awt.Color(100, 149, 237));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(100, 149, 237));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ADD WEEKEND DETAILS");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 1254, Short.MAX_VALUE)
                .addGap(67, 67, 67))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        edit_body.setBackground(new java.awt.Color(100, 149, 237));
        edit_body.setToolTipText("");

        jPanel6.setBackground(new java.awt.Color(100, 149, 237));

        btn_weekday.setBackground(new java.awt.Color(153, 153, 0));
        btn_weekday.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_weekday.setForeground(new java.awt.Color(255, 255, 255));
        btn_weekday.setText("Weekday");
        btn_weekday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_weekdayMousePressed(evt);
            }
        });

        btn_weekend.setBackground(new java.awt.Color(153, 153, 0));
        btn_weekend.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_weekend.setForeground(new java.awt.Color(255, 255, 255));
        btn_weekend.setText("Weekend");
        btn_weekend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_weekendMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_weekday)
                    .addComponent(btn_weekend))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btn_weekday)
                .addGap(40, 40, 40)
                .addComponent(btn_weekend)
                .addContainerGap(488, Short.MAX_VALUE))
        );

        body.setBackground(new java.awt.Color(100, 149, 237));
        body.setToolTipText("");
        body.setLayout(new javax.swing.BoxLayout(body, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout edit_bodyLayout = new javax.swing.GroupLayout(edit_body);
        edit_body.setLayout(edit_bodyLayout);
        edit_bodyLayout.setHorizontalGroup(
            edit_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, edit_bodyLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        edit_bodyLayout.setVerticalGroup(
            edit_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edit_bodyLayout.createSequentialGroup()
                .addGroup(edit_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(edit_body, java.awt.BorderLayout.CENTER);

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1331, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_weekdayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_weekdayMousePressed
        body.removeAll();
        body.add(new Weekday_Edit());
        body.repaint();
        body.revalidate();
        
        btn_weekend.setBackground(new Color(153, 153, 0));
        btn_weekday.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_btn_weekdayMousePressed

    private void btn_weekendMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_weekendMousePressed
        body.removeAll();
        
        body.add(new Weekend_Edit());
        body.repaint();
        body.revalidate();
        
        btn_weekday.setBackground(new Color(153, 153, 0));
        btn_weekend.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_btn_weekendMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JButton btn_weekday;
    private javax.swing.JButton btn_weekend;
    private javax.swing.JPanel edit_body;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
